[package]
name = "node_napi"
version = "0.1.1"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
license = "LGPL-3.0"

[dependencies]
failure = "0.1.3"
failure_derive = "0.1.3"
serde = "1.0.80"
serde_derive = "1.0.80"
